name: vfocused_app
description: "A new Flutter project."

publish_to: "none"

version: 1.4.9+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  
  flutter_riverpod: ^2.6.1
  sleek_circular_slider: ^2.1.0
  flutter_svg: ^2.1.0
  audioplayers: ^6.4.0
  flutter_local_notifications: ^19.2.1
  smooth_page_indicator: ^1.2.1
  shared_preferences: ^2.5.3
  # flutter_background_service: ^5.1.0
  # isar: ^3.1.0+1
  # isar_flutter_libs: ^3.1.0+1
  # path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  # isar_generator: ^3.1.0+1
  # build_runner: ^2.4.13

  flutter_launcher_icons: "^0.14.4"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/sounds/
  

  fonts:
    - family: Orbitron
      fonts:
        - asset: assets/fonts/Orbitron/Orbitron-Regular.ttf
        - asset: assets/fonts/Orbitron/Orbitron-SemiBold.ttf
          weight: 700

    - family: SpaceGrotesk
      fonts:
        - asset: assets/fonts/Space_Grotesk/SpaceGrotesk-Regular.ttf
        - asset: assets/fonts/Space_Grotesk/SpaceGrotesk-SemiBold.ttf
          weight: 700

    - family: Sora
      fonts:
        - asset: assets/fonts/Sora/Sora-Regular.ttf
        - asset: assets/fonts/Sora/Sora-SemiBold.ttf
          weight: 600


  